# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BMxZABKv3TagLUYfO9JANseacEtkgX8d
"""

a = int(input())
b = int(input())
print(a//b)
print(a/b)